In [2]:
#Find probability that given input [2,3] has a label 0 or a label 1? using naive bayes
#Here 2 is only checked for v1 and 3 only for v2

In [4]:
import numpy as np
from numpy import asarray as npa
from matplotlib import pyplot as plt
%matplotlib inline
import random

In [10]:
dataSet = [1,2,3]
labSet = [0,1]
sz = 20 

#v1 = npa([random.choice(dataSet) for i in range(sz)])
#v2 = npa([random.choice(dataSet) for i in range(sz)])
#lab = npa([random.choice(labSet) for i in range(sz)])

v1 = npa([1, 3, 3, 2, 1, 2, 2, 2, 3, 3, 2, 2, 2, 1, 3, 2, 2, 3, 2, 2])
v2 = npa([2, 1, 3, 1, 2, 3, 3, 1, 1, 1, 1, 3, 2, 1, 2, 2, 1, 2, 2, 1])
lab =  npa([1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

print v1, "\n", v2, "\n", lab

[1 3 2 3 2 1 2 3 2 3 1 1 1 3 1 1 1 3 3 3] 
[2 1 1 1 3 1 3 3 3 1 2 3 2 2 3 3 2 3 2 3] 
[1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0]


In [12]:
c2 = c3 = 0
for i in range(sz):
    if v1[i] == 2:
        c2+=1
    if v2[i] == 3:
        c3 += 1
        
print c2+c3

13
